# -*- coding: utf-8 -*-
"""boj19532_kdohwn3934

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EjK3uBtkC1K5ugioVaSE46HTmTF7eILW
"""

a,b,c,d,e,f=map(int,input().split())

for i in range(-1000,1000):
   for j in range(-1000,1000):
     if a*i+b*j == c and d*i + e*j == f:
       x = int(i)
       y = int(j)
       print(x,y)
       break