# -*- coding: utf-8 -*-
"""boj2798_kdohwn3934

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EjK3uBtkC1K5ugioVaSE46HTmTF7eILW
"""

n,m=map(int,input().split())

card = list(map(int,input().split()))
sum_list=[]
sum=0
for x in card:
  for y in card:
    for z in card:
       if not x==y:
         if not y==z:
           if not x==z:
             k=x+y+z
             if k <= m:
               sum_list.append(k)
sum=max(sum_list)

print(sum)