# -*- coding: utf-8 -*-
"""boj2231_kdohwn3934

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EjK3uBtkC1K5ugioVaSE46HTmTF7eILW
"""

n = int(input())
nk=len(str(n))

for k in range(n-9*nk-1,n+9*nk+1):
  x=k
  sum=0
  while True:  
    r = x%10
    sum += r
    x //=10
    if x <= 0:
      break
  if k+sum == n:
    print(k)
    break
  if k == n+9*nk:
    print(0)