# -*- coding: utf-8 -*-
"""boj3040_kdohwn3934

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EjK3uBtkC1K5ugioVaSE46HTmTF7eILW
"""

arr=[]
sum = 0
for i in range(9):
    x = int(input())
    sum +=x
    arr.append(x)

for i in range(9):
    for j in range(9):
        if i == j:
            continue
        if sum - arr[i]- arr[j]  == 100:
            arr[i]=-1
            arr[j]=-1
for i in range(9):
    if arr[i] != -1:
        print(arr[i])